#
# Advanced Kubernetes training by Bitnami
#
# WordPress deployment

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
    type: frontend
spec:
  # With one replica it is enough
  replicas: 1
  # Pod definition
  template:
    metadata:
      # Some basic metadata to be later used with services
      labels:
        app: wordpress
        type: frontend
    spec:
      containers:
        # Image information
        - name: wordpress
          image: bitnami/wordpress:4.9.2-r1
          # Port information for later use with services
          ports:
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port
          # Environment variables for configuration
          env:
            # Database credentials
            - name: MARIADB_HOST
              value: mariadb-service
            - name: MARIADB_PORT_NUMBER
              value: "3306"
            - name: WORDPRESS_DATABASE_USER
              value: bn_wordpress
            - name: WORDPRESS_DATABASE_PASSWORD
              value: securepassword123
            - name: WORDPRESS_DATABASE_NAME
              value: bitnami_wordpress
              # Some Wordpress basic data
            - name: WORDPRESS_BLOG_NAME
              value: Advanced Kubernetes Volume Example
            - name: WORDPRESS_PASSWORD
              value: exercise01
          # Mount the volume in the container
          volumeMounts:
            - mountPath: /bitnami
              name: wordpress-vol
      # List of volumes
      volumes:
        - name: wordpress-vol
          hostPath:
            # directory location on host
            path: /tmp/wordpress
            # this field is optional
            type: Directory
